/**
 * What this build ships.
 *
 * Onkar, 2026-09-01: ship the photograph version, park the 3D models for a
 * future update. The models are finished and confirmed — they are not deleted
 * and not regressed; the seventeen GLBs sit in `_parked/models/`, outside
 * `public/`, so nothing is served or deployed. See `_parked/README.md`.
 *
 * This flag is read at the CALL SITE (`app/products/[slug]/page.tsx`), never
 * inside `data/models.ts` — that file is generated by
 * `tools/publish_models.py` and any hand edit is lost on the next run.
 *
 * To ship them: move `_parked/models` back to `public/models`, set this true,
 * rebuild. Nothing else changes — the viewer, the index and the pipeline are
 * all still here.
 */
export const SHIP_3D_MODELS = false;
