// GENERATED by tools/publish_models.py - do not edit by hand.
// One entry per confirmed 3D model that has a product page.
// Regenerate after re-exporting: python tools/publish_models.py

export const MODELS: Record<string, { mb: number }> = {
  "all-angle-thermometers": { mb: 1.17 },
  "bi-metal-thermometers": { mb: 1.15 },
  "capsule-gauge": { mb: 1.15 },
  "contact-gauges": { mb: 1.21 },
  "diaphragm-sealed-gauges": { mb: 1.17 },
  "differential-gauges": { mb: 1.15 },
  "gas-in-metal-thermometers": { mb: 1.11 },
  "gas-with-contact-thermometers": { mb: 1.21 },
  "high-range-pressure-gauge": { mb: 1.14 },
  "light-duty-economy-gauge": { mb: 1.17 },
  "precision-test-gauges": { mb: 1.14 },
  "process-gauges": { mb: 1.19 },
  "solid-front-case-liquid-fillable": { mb: 1.16 },
  "stainless-steel-case-liquid-fillable": { mb: 1.18 },
  "test-gauges": { mb: 1.19 },
  "triclover-gauge": { mb: 1.16 },
  "utility-commercial-gauges": { mb: 1.17 },
};

/** Path to a product's model, or null when it has none. */
export function modelFor(slug: string): string | null {
  return slug in MODELS ? `/models/${slug}.glb` : null;
}
